apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: ow800hr22-python 
  janus-idp.io/tekton: ow800hr22-python
  backstage.io/kubernetes-id: ow800hr22-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ow800hr22-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml