apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ow800hr22-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ow800hr22-python 
  name: ow800hr22-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ow800hr22-python 
